### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by brahimdidi** [Ewoskyx/awesome_books#6]
HI Ersoy, Great job on your project. It looks great, however,4 I would like to suggest some improvements you could do to make it cleaner.

-it would look better if you used the same font family and font size for the header on the different pages of the app.
-it would be more professional to mention to link your GitHub and email or LinkedIn accounts.

Thanks.

**Comment by Ewoskyx** [comment]
Hello @brahimdidi, thank you for the suggestions. We will check for it.
